version: '3'

services:
  punchingbag:
    build:
      context: ./punching-bag
    restart: unless-stopped
    container_name: punchingbag
    networks:
      - funny
  firebox:
    build:
      context: ./firebox
    restart: unless-stopped
    container_name: firebox
    networks:
      - funny
  bot:
    build:
      context: ./bot
    restart: unless-stopped
    networks:
      - funny
    volumes:
      - gamerbot-store:/gb-data
    depends_on:
      - punchingbag
      - firebox

volumes:
  gamerbot-store:

networks:
  funny:
    driver: bridge