version: '3'

services:
  punchingbag:
    build:
      context: ./punching-bag
    restart: unless-stopped
    container_name: punchingbag
    networks:
      - funny
  openboi:
    build:
      context: ./openboi
    restart: unless-stopped
    container_name: openboi
    networks:
      - funny
  bot:
    build:
      context: ./bot
    restart: unless-stopped
    networks:
      - funny
    volumes:
      - gamerbot-store:/gb-data
    depends_on:
      - punchingbag

volumes:
  gamerbot-store:

networks:
  funny:
    driver: bridge