version: '3'

services:
  punchingbag:
    build:
      context: ./punching-bag
    restart: unless-stopped
    container_name: punchingbag
    networks:
      - funny
    volumes:
      - gamerbot-store:/home
      - second-volume:/path/to/second/volume
  bot:
    build:
      context: ./bot
    restart: unless-stopped
    container_name: theboy
    networks:
      - funny
    volumes:
      - gamerbot-store:/gb-data
    depends_on:
      - punchingbag

volumes:
  gamerbot-store:
  second-volume:

networks:
  funny:
    driver: bridge